version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # needed for live reloading in local development
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - db
    networks:
      - share-a-ride-network
    command: ["air"]

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=share_a_ride
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - share-a-ride-network

volumes:
  postgres_data:

networks:
  share-a-ride-network:
    driver: bridge 