name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install tools
          run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
            go install github.com/securego/gosec/v2/cmd/gosec@latest
            go install github.org/x/vuln/cmd/govulncheck@latest

      - name: Run linter
        run: golangci-lint run --timeout 5m

      - name: Static analysis
        run govet ./...

      - name: Security check
        run gosec ./...

      - name: Vulnerability scan
        run govulncheck ./...
      
      - name: Run tests
        run: go test -v -cover ./...
